name: Python package

on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master


jobs:
  bake:
    runs-on: ubuntu-latest
    steps:
      -
        name: "checks out the git repo"
        uses: actions/checkout@v2
      -
        name: "install python"
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - 
        name: "install dependencies"
        run:  "pip install black flake8"
      -
        name: "set up docker buildx"
        uses: docker/setup-buildx-action@v1
      -
        name: "build docker, push"
        uses: docker/back-action@master
        with:
          push: false
